apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qube-lite
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kodebros-dev/qube-infrastructure.git
    path: qube-lite
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - PrunePropagationPolicy=Foreground
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 10
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 10m
